export const ABBREV_TO_STATE: Record<string, string> = {
  AK: 'Alaska',
  AL: 'Alabama',
  AR: 'Arkansas',
  AS: 'American Samoa',
  AZ: 'Arizona',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DC: 'District of Columbia',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  GU: 'Guam',
  HI: 'Hawaii',
  IA: 'Iowa',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  MA: 'Massachusetts',
  MD: 'Maryland',
  ME: 'Maine',
  MI: 'Michigan',
  MN: 'Minnesota',
  MO: 'Missouri',
  MS: 'Mississippi',
  MT: 'Montana',
  NC: 'North Carolina',
  ND: 'North Dakota',
  NE: 'Nebraska',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NV: 'Nevada',
  NY: 'New York',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VA: 'Virginia',
  VI: 'Virgin Islands',
  VT: 'Vermont',
  WA: 'Washington',
  WI: 'Wisconsin',
  WV: 'West Virginia',
  WY: 'Wyoming',
};

export const STATE_TO_ABBREV: Record<string, string> = {
  Alabama: 'AL',
  Alaska: 'AK',
  'American Samoa': 'AS',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District Of Columbia': 'DC',
  'Federated States Of Micronesia': 'FM',
  Florida: 'FL',
  Georgia: 'GA',
  Guam: 'GU',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  'Marshall Islands': 'MH',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Northern Mariana Islands': 'MP',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Palau: 'PW',
  Pennsylvania: 'PA',
  'Puerto Rico': 'PR',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  'Virgin Islands': 'VI',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

export const STATES_DROPDOWN = [
  ['Alaska', 'AK'],
  ['Alabama', 'AL'],
  ['Arkansas', 'AR'],
  ['American Samoa', 'AS'],
  ['Arizona', 'AZ'],
  ['California', 'CA'],
  ['Colorado', 'CO'],
  ['Connecticut', 'CT'],
  ['District of Columbia', 'DC'],
  ['Delaware', 'DE'],
  ['Florida', 'FL'],
  ['Georgia', 'GA'],
  ['Guam', 'GU'],
  ['Hawaii', 'HI'],
  ['Iowa', 'IA'],
  ['Idaho', 'ID'],
  ['Illinois', 'IL'],
  ['Indiana', 'IN'],
  ['Kansas', 'KS'],
  ['Kentucky', 'KY'],
  ['Louisiana', 'LA'],
  ['Massachusetts', 'MA'],
  ['Maryland', 'MD'],
  ['Maine', 'ME'],
  ['Michigan', 'MI'],
  ['Minnesota', 'MN'],
  ['Missouri', 'MO'],
  ['Mississippi', 'MS'],
  ['Montana', 'MT'],
  ['North Carolina', 'NC'],
  ['North Dakota', 'ND'],
  ['Nebraska', 'NE'],
  ['New Hampshire', 'NH'],
  ['New Jersey', 'NJ'],
  ['New Mexico', 'NM'],
  ['Nevada', 'NV'],
  ['New York', 'NY'],
  ['Ohio', 'OH'],
  ['Oklahoma', 'OK'],
  ['Oregon', 'OR'],
  ['Pennsylvania', 'PA'],
  ['Puerto Rico', 'PR'],
  ['Rhode Island', 'RI'],
  ['South Carolina', 'SC'],
  ['South Dakota', 'SD'],
  ['Tennessee', 'TN'],
  ['Texas', 'TX'],
  ['Utah', 'UT'],
  ['Virginia', 'VA'],
  ['Virgin Islands', 'VI'],
  ['Vermont', 'VT'],
  ['Washington', 'WA'],
  ['Wisconsin', 'WI'],
  ['West Virginia', 'WV'],
  ['Wyoming', 'WY'],
];

export const STATE_TO_INMATE_DB = {
  AK: { link: '' },
  AL: { link: 'http://www.doc.state.al.us/InmateSearch' },
  AR: { link: 'https://corrections.az.gov/public-resources/inmate-datasearch' },
  AS: { link: '' },
  AZ: { link: 'https://corrections.az.gov/public-resources/inmate-datasearch' },
  CA: { link: 'https://inmatelocator.cdcr.ca.gov/search.aspx' },
  CO: { link: 'http://www.doc.state.co.us/oss/' },
  CT: { link: 'http://www.ctinmateinfo.state.ct.us/searchop.asp' },
  DC: { link: '' },
  DE: { link: '' },
  FL: { link: 'http://www.dc.state.fl.us/OffenderSearch/Search.aspx' },
  GA: {
    link:
      'http://www.dcor.state.ga.us/GDC/OffenderQuery/jsp/OffQryForm.jsp?Institution=',
  },
  GU: { link: '' },
  HI: { link: '' },
  IA: { link: 'https://doc.iowa.gov/offender/search' },
  ID: { link: 'https://www.idoc.idaho.gov/content/prisons/offender_search' },
  IL: {
    link: 'https://www2.illinois.gov/idoc/offender/pages/inmatesearch.aspx',
  },
  IN: { link: 'https://www.in.gov/apps/indcorrection/ofs/ofs' },
  KS: { link: 'https://kdocrepository.doc.ks.gov/kasper/' },
  KY: { link: 'http://kool.corrections.ky.gov/' },
  LA: { link: '' },
  MA: { link: '' },
  MD: { link: 'http://www.dpscs.state.md.us/inmate/' },
  ME: {
    link:
      'https://www1.maine.gov/cgi-bin/online/mdoc/search-and-deposit/search.pl?Search=Continue',
  },
  MI: { link: 'http://mdocweb.state.mi.us/OTIS2/otis2.aspx' },
  MN: { link: 'https://coms.doc.state.mn.us/PublicViewer' },
  MO: { link: 'https://web.mo.gov/doc/offSearchWeb/welcome.do' },
  MS: { link: 'https://www.ms.gov/mdoc/inmate' },
  MT: { link: 'https://app.mt.gov/conweb/' },
  NC: {
    link: 'https://webapps.doc.state.nc.us/opi/offendersearch.do?method=view',
  },
  ND: { link: 'http://www.nd.gov/docr/offenderlkup/index.asp' },
  NE: { link: 'http://dcs-inmatesearch.ne.gov/Corrections/COR_input.html' },
  NH: { link: 'http://business.nh.gov/inmate_locator/' },
  NJ: { link: 'https://www20.state.nj.us/DOC_Inmate/inmatesearch' },
  NM: { link: 'http://search.cd.nm.gov/' },
  NV: { link: 'http://167.154.2.76/inmatesearch/form.php' },
  NY: { link: 'http://nysdoccslookup.doccs.ny.gov/' },
  OH: { link: 'https://appgateway.drc.ohio.gov/OffenderSearch' },
  OK: { link: 'https://okoffender.doc.ok.gov/' },
  OR: { link: 'http://docpub.state.or.us/OOS/searchCriteria.jsf' },
  PA: { link: 'http://inmatelocator.cor.pa.gov/#/' },
  PR: { link: '' },
  RI: { link: 'http://www.doc.ri.gov/inmate_search/search.php' },
  SC: { link: 'http://public.doc.state.sc.us/scdc-public/' },
  SD: { link: 'https://doc.sd.gov/adult/lookup/' },
  TN: { link: 'https://apps.tn.gov/foil-app/results.jsp' },
  TX: { link: 'https://offender.tdcj.texas.gov/OffenderSearch/index.jsp' },
  UT: { link: 'https://corrections.utah.gov/index.php/2014-10-30-20-13-59' },
  VA: { link: 'https://vadoc.virginia.gov/offenders/locator/index.aspx' },
  VI: { link: '' },
  VT: {
    link:
      'https://omsweb.public-safety-cloud.com/jtclientweb/(S(w42wllbjj4dtbxy4gvmfk4q4))/jailtracker/index/Vermont',
  },
  WA: { link: 'https://www.doc.wa.gov/information/inmate-search/default.aspx' },
  WI: { link: 'https://appsdoc.wi.gov/lop/home.do' },
  WV: { link: 'https://apps.wv.gov/ois/offendersearch/doc' },
  WY: { link: 'http://wdoc-loc.wyo.gov/' },
};
